### ISSUE TITLE
关于youtube的广告拦截问题

### ISSUE THREAD

**Issue by mq00fc** [zu1k/good-mitm#74]
尊敬的开发者您好

我将statsh的复写设置打算放入服务器上的mitm中，规则如下
```
#!desc =支持pip，后台播放
#!author = Maasea 
#!homepage=https://whatshub.top
#!icon = https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png
name: YouTubequguanggao
desc: 支持pip，后台播放
http:
  mitm:
    - "-redirector*.googlevideo.com"
    - "*.googlevideo.com"
    - "www.youtube.com"
    - "s.youtube.com"
    - "youtubei.googleapis.com"
  script:
    - match: ^https?:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch)
      name: YouTubequguanggao1
      type: response
      require-body: true
      binary-mode: true
      timeout: 10
  rewrite:
    - (^https?:\/\/[\w-]+\.googlevideo\.com\/(?!dclk_video_ads).+?)&ctier=L(&.+?),ctier,(.+) $1$2$3 302
    - ^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?)).+&oad - reject-200
    - ^https?:\/\/(www|s)\.youtube\.com\/api\/stats\/ads - reject-200
    - ^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking) - reject-200
    - ^https?:\/\/s\.youtube\.com\/api\/stats\/qoe\?adcontext - reject-200
script-providers:
  YouTubequguanggao1:
    url: https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/dist/youtube.response.preview.js
    interval: 86400
```

拦截工作可以进行，但是画中画（后台播放）没法实现

我参考了文档，没有发现可以插入js的效果，是否可以考虑增加实现？

谢谢，以上
